### ISSUE TITLE
Wrong kind for bend

### ISSUE THREAD

**Issue by wlfrdssn** [perliedman/svg-control-descriptions#3]
Bend is placed in kind G but should be in kind F.

**Comment by perliedman** [comment]
Interesting, I notice that in Purple Pen's `symbols.xml`, "bend" is in fact listed twice, once with kind "F" and again with kind "G". So the issue is that this library assumes a symbol can only have one kind.

So, I guess the property "kind" should really be "kinds" and a list of possible values.

**Comment by perliedman** [comment]
Ok, so the reason the symbol appears twice is that it changed column between the 2004 standard and 2018 standard. As written, svg-control-descriptions were not aware of different standards.

I have updated the code so you can filter symbols on standard (defaulting to 2018) and updated the package (version 2.1.0) with 2018 symbols, where "bend" has the correct column.
